# Generated by Django 3.2.6 on 2023-10-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASI_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('grupo_sanguineo', models.CharField(max_length=50)),
                ('nombre_eps', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('dependecia', models.CharField(max_length=50)),
            ],
        ),
    ]
