# Generated by Django 3.2.6 on 2023-10-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASI_app', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagen_diagnostico',
            field=models.ImageField(null=True, upload_to='imagenes_diagnostico'),
        ),
    ]
