# Generated by Django 3.2.6 on 2023-10-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASI_app', '0003_paciente_imagen_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='imagen_diagnostico',
            field=models.ImageField(null=True, upload_to='imagenes_diagnosticas'),
        ),
    ]
